### ISSUE TITLE
Fetch and Display contents from search to dashboard

### ISSUE THREAD

**Issue by r-ush** [r-ush/tcdr-frontend#1]
add the response from API in the search bar to local storage and then display the results in the component

**Comment by MaximeKoitsalu** [comment]
Hi, I can take on this task :) @r-ush

**Comment by r-ush** [comment]
Go on! @MaximeKoitsalu

**Comment by MaximeKoitsalu** [comment]
@r-ush do you have any examples of the api response or instructions how to setup my own backend :)? Right now, the api endpoint points to http://localhost:5000/sci

**Comment by r-ush** [comment]
I'll share the a dummy response

**Comment by r-ush** [comment]
https://github.com/liuhh02/tcdr-ml this is the repo for the backend, you can check the response for the scilit section here @MaximeKoitsalu

**Comment by r-ush** [comment]
Thanks @MaximeKoitsalu !
